let listeA = {
  ' do Mineur Mélodique' : ['do', 'ré', 'ré#', 'fa', 'sol', 'la', 'si', "",],
  ' do# Mineur Mélodique' : ['do#', 'ré#', 'mi', 'fa#', 'sol#', 'la#', 'do', "",],
  ' ré Mineur Mélodique' : ['ré', 'mi', 'fa', 'sol', 'la', 'si', 'do#', ""],
  ' ré# Mineur Mélodique' : ['ré#', 'fa', 'fa#', 'sol#', 'la#', 'do', 'ré', ""],
  ' mi Mineur Mélodique' : ['mi', 'fa#', 'sol', 'la', 'si', 'do#', 'ré#', ""],
  ' fa Mineur Mélodique' : ['fa', 'sol', 'sol#', 'la#', 'do', 'ré', 'mi', ""],
  ' fa# Mineur Mélodique' : ['fa#', 'sol#', 'la', 'si', 'do#', 'ré#', 'fa', ""],
  ' sol Mineur Mélodique' : ['sol', 'la', 'la#', 'do', 'ré', 'mi', 'fa#', ""],
  ' sol# Mineur Mélodique' : ['sol#', 'la#', 'si', 'do#', 'ré#', 'fa', 'sol', ""],
  ' la Mineur Mélodique' : ['la', 'si', 'do', 'ré', 'mi', 'fa#', 'sol#', ""],
  ' la# Mineur Mélodique' : ['la#', 'do', 'do#', 'ré#', 'fa', 'sol', 'la', ""],
  ' si Mineur Mélodique' : ['si', 'do#', 'ré', 'mi', 'fa#', 'sol#', 'la#', ""],

  'do Mineure Harmonique' : ['do','ré','ré#','fa','sol','sol#','si', ""],
  'do# Mineure harmonique' : ['do#', 'ré#', 'mi', 'fa#', 'sol#', 'la', 'si', ""],
  'ré Mineure harmonique' : ['ré', 'mi', 'fa', 'sol', 'la', 'la#', 'do#', ""],
  'ré# Mineure Harmonique' : ['ré#','fa','fa#','sol#','la#','si','ré', ""],
  'mi Mineure harmonique' : ['mi', 'fa#', 'sol', 'la', 'si', 'do', 'ré#', ""],
  'fa Mineure harmonique' : ['fa', 'sol', 'sol#', 'la#', 'do', 'ré', 'mi', ""],
  'fa# Mineure Harmonique' : ['fa#','sol#','la','si','do#','ré','fa', ""],
  'sol Mineure harmonique' : ['sol', 'la', 'la#', 'do', 'ré', 'ré#', 'fa#', ""],
  'sol# Mineure Harmonique' : ['sol#','la#','si','do#','ré#','mi','sol', ""],
  'la Mineure harmonique' : ['la', 'si', 'do', 'ré', 'mi', 'fa', 'sol#', ""],
  'la# Mineure harmonique' : ['la#', 'do', 'do#', 'ré#', 'fa', 'fa#', 'la', ""],
  'si Mineure harmonique' : ['si', 'do#', 'ré', 'mi', 'fa#', 'sol', 'la#', ""],


  'do Mineur naturel' : ['do', 'ré', 'ré#', 'fa', 'sol', "sol#", "la#", ""], 
  'do# Mineur naturel' : ['do#', 'ré#', 'mi', 'fa#', 'sol#', "la", "si", ""], 
  'ré Mineur naturel' : ['ré', 'mi', 'fa', 'sol', 'la', "la#", "do", ""], 
  'ré# Mineur naturel' : ['ré#', 'fa', 'fa#', 'sol#', 'la#', "do", "do#", ""], 
  'mi Mineur naturel' : ['mi', 'fa#', 'sol', 'la', 'si', "do", "ré", ""], 
  'fa Mineur naturel' : ['fa', 'sol', 'sol#', 'la#', 'do', "do#", "ré#", ""], 
  'fa# Mineur naturel' : ['fa#', 'sol#', 'la', 'si', 'do#', "ré", "mi", ""], 
  'sol Mineur naturel' : ['sol', 'la', 'la#', 'do', 'ré', "ré#", "fa", ""], 
  'sol# Mineur naturel' : ['sol#', 'la#', 'si', 'do#', 'ré#', "mi", "fa#", ""], 
  'la Mineur naturel' : ['la', 'si', 'do', 'ré', 'mi', "fa", "sol", ""], 
  'la# Mineur naturel' : ['la#', 'do', 'do#', 'ré#', 'fa', "fa#", "sol#", ""], 
  'si/do♭ Mineur naturel' : ['si', 'do#', 'ré', 'mi', 'fa#', "sol", "la", ""], 

  'do Pentatonique majeure' : ['do', 'ré', 'mi', 'sol', 'la', "", ""],
  'do# Pentatonique majeure' : ['do#', 'ré#', 'fa', 'sol#', 'la#', "", ""],
  'ré Pentatonique majeure' : ['ré', 'mi', 'fa#', 'la', 'si', "", ""],
  'ré# Pentatonique majeure' : ['ré#', 'fa', 'sol', 'la#', 'do', "", ""],
  'mi Pentatonique majeure' : ['mi', 'fa#', 'sol#', 'si', 'do#', "", ""],
  'fa Pentatonique majeure' : ['fa', 'sol', 'la', 'do', 'ré', "", ""],
  'fa# Pentatonique majeure' : ['fa#', 'sol#', 'la#', 'do#', 'ré#', "", ""],
  'sol Pentatonique majeure' : ['sol', 'la', 'si', 'ré', 'mi', "", ""],
  'sol# Pentatonique majeure' : ['sol#', 'la#', 'do', 'ré#', 'fa', "", ""],
  'la Pentatonique majeure' : ['la', 'si', 'do#', 'mi', 'fa#', "", ""],
  'la# Pentatonique majeure' : ['la#', 'do', 'ré', 'fa', 'sol', "", ""],
  'si Pentatonique majeure' : ['si', 'do#', 'ré#', 'fa#', 'sol#', "", ""],

  'Do Pentatonique Mineure' : ["do", "ré#", "fa", "sol", "la#","",""],
  'Do# Pentatonique Mineure' : ["do#", "mi", "fa#", "sol#", "si","",""],
  'Ré Pentatonique Mineure' : ["ré", "fa", "sol", "la", "do","",""],
  'Ré# Pentatonique Mineure' : ["ré#", "fa#", "sol#", "la#", "do#","",""],
  'Mi Pentatonique Mineure' : ["mi", "sol", "la", "si", "ré","","",""],
  'Fa Pentatonique Mineure' : ["fa", "sol#", "la#", "do", "ré#","",""],
  'Fa# Pentatonique Mineure' : ["fa#", "la", "si", "do#", "mi","",""],
  'Sol Pentatonique Mineure' : ["sol", "la#", "do", "ré", "fa","",""],
  'Sol# Pentatonique Mineure' : ["sol#", "si", "do#", "mi", "fa#","",""],
  'La Pentatonique Mineure' : ["la", "do", "ré", "mi", "sol","",""],
  'La# Pentatonique Mineure' : ["la#", "do#", "ré#", "fa", "sol#","",""],
  'Si Pentatonique Mineure' : ["si", "ré", "mi", "fa#", "la","",""],

  'Do Blues Mineur' : ["do", "ré#", "fa", "fa#", "sol", "la#",""],
  'Do# Blues Mineur' : ["do#", "mi", "fa#", "sol", "sol#", "si",""],
  'Ré Blues Mineur' : ["ré", "fa", "sol", "sol#", "la", "do",""],
  'Ré# Blues Mineur' : ["ré#", "fa#", "sol#", "la", "la#", "do#",""],
  'Mi Blues Mineur' : ["mi", "sol", "la", "la#", "si", "ré",""],
  'Fa Blues Mineur' : ["fa", "sol#", "la#", "si", "do", "ré#",""],
  'Fa# Blues Mineur' : ["fa#", "la", "si", "do", "do#", "mi",""],
  'Sol Blues Mineur' : ["sol", "la#", "do", "do#", "ré", "fa",""],
  'Sol# Blues Mineur' : ["sol#", "si", "do#", "ré", "ré#", "fa#",""],
  'La Blues Mineur' : ["la", "do", "ré", "ré#", "mi", "sol",""],
  'La# Blues Mineur' : ["la#", "do#", "ré#", "mi", "fa", "sol#",""],
  'Si Blues Mineur' : ["do", "ré#", "fa", "fa#", "sol", "la#",""],

  'Do Blues Majeur' : ["do", "ré", "ré#", "mi", "sol", "la",""],
  'Do# Blues Majeur' : ["do#", "ré#", "mi", "fa", "sol#", "la#",""],
  'Ré Blues Majeur' : ["ré", "mi", "fa", "fa#", "la", "si",""],
  'Ré# Blues Majeur' : ["ré#", "fa", "fa#", "sol", "la#", "do",""],
  'Mi Blues Majeur' : ["mi", "fa#", "sol", "sol#", "si", "do#",""],
  'Fa Blues Majeur' : ["fa", "sol", "sol#", "la", "do", "ré",""],
  'Fa# Blues Majeur' : ["fa#", "sol#", "la", "la#", "do#", "ré#",""],
  'Sol Blues Majeur' : ["sol", "la", "la#", "si", "ré", "mi",""],
  'Sol# Blues Majeur' : ["sol#", "la#", "si", "do", "ré#", "fa",""],
  'La Blues Majeur' : ["la", "si", "do", "do#", "mi", "fa#",""],
  'La# Blues Majeur' : ["la#", "do", "do#", "ré", "fa", "sol",""],
  'Si Blues Majeur' : ["si", "do#", "ré", "ré#", "fa#", "sol#",""],

'Do Ionique (parent: Do majeur)' : ["do", "ré", "mi", "fa", "sol", "la", "si",""],
  'Do# Ionique (parent: Do# majeur)' : ["do#", "ré#", "fa", "fa#", "sol#", "la#", "do",""],
  'Ré Ionique (parent: Ré majeur)' : ["ré", "mi", "fa#", "sol", "la", "si", "do#",""],
  'Ré# Ionique (parent: Ré# majeur)' : ["ré#", "fa", "sol", "sol#", "la#", "do", "ré",""],
  'Mi Ionique (parent: Mi majeur)' : ["mi", "fa#", "sol#", "la", "si", "do#", "ré#",""],
  'Fa Ionique (parent: Fa majeur)' : ["fa", "sol", "la", "la#", "do", "ré", "mi",""],
  'Fa# Ionique (parent: Fa# majeur)' : ["fa#", "sol#", "la#", "si", "do#", "ré#", "fa",""],
  'Sol Ionique (parent: Sol majeur)' : ["sol", "la", "si", "do", "ré", "mi", "fa#",""],
  'Sol# Ionique (parent: Sol# majeur)' : ["sol#", "la#", "do", "do#", "ré#", "fa", "sol",""],
  'La Ionique (parent: La majeur)' : ["la", "si", "do#", "ré", "mi", "fa#", "sol#",""],
  'La# Ionique (parent: La# majeur)' : ["la#", "do", "ré", "ré#", "fa", "sol", "sol#",""],
  'Si Ionique (parent: Si majeur)' : ["si", "do#", "ré#", "mi", "fa#", "sol#", "la#",""],

  // Dorian - parent is a whole step below
  'Do Dorien (parent: La# majeur)' : ["do", "ré", "ré#", "fa", "sol", "la", "la#",""],
  'Do# Dorien (parent: Si majeur)' : ["do#", "ré#", "mi", "fa#", "sol#", "la#", "si",""],
  'Ré Dorien (parent: Do majeur)' : ["ré", "mi", "fa", "sol", "la", "si", "do",""],
  'Ré# Dorien (parent: Do# majeur)' : ["ré#", "fa", "fa#", "sol#", "la#", "do", "do#",""],
  'Mi Dorien (parent: Ré majeur)' : ["mi", "fa#", "sol", "la", "si", "do#", "ré",""],
  'Fa Dorien (parent: Ré# majeur)' : ["fa", "sol", "sol#", "la#", "do", "ré", "ré#",""],
  'Fa# Dorien (parent: Mi majeur)' : ["fa#", "sol#", "la", "si", "do#", "ré#", "mi",""],
  'Sol Dorien (parent: Fa majeur)' : ["sol", "la", "la#", "do", "ré", "mi", "fa",""],
  'Sol# Dorien (parent: Fa# majeur)' : ["sol#", "la#", "si", "do#", "ré#", "fa", "fa#",""],
  'La Dorien (parent: Sol majeur)' : ["la", "si", "do", "ré", "mi", "fa#", "sol",""],
  'La# Dorien (parent: Sol# majeur)' : ["la#", "do", "do#", "ré#", "fa", "sol", "sol#",""],
  'Si Dorien (parent: La majeur)' : ["si", "do#", "ré", "mi", "fa#", "sol#", "la",""],

  // Phrygian - parent is a major third below
  'Do Phrygien (parent: Sol# majeur)' : ["do", "do#", "ré#", "fa", "sol", "sol#", "la#",""],
  'Do# Phrygien (parent: La majeur)' : ["do#", "ré", "mi", "fa#", "sol#", "la", "si",""],
  'Ré Phrygien (parent: La# majeur)' : ["ré", "ré#", "fa", "sol", "la", "la#", "do",""],
  'Ré# Phrygien (parent: Si majeur)' : ["ré#", "mi", "fa#", "sol#", "la#", "si", "do#",""],
  'Mi Phrygien (parent: Do majeur)' : ["mi", "fa", "sol", "la", "si", "do", "ré",""],
  'Fa Phrygien (parent: Do# majeur)' : ["fa", "fa#", "sol#", "la#", "do", "do#", "ré#",""],
  'Fa# Phrygien (parent: Ré majeur)' : ["fa#", "sol", "la", "si", "do#", "ré", "mi",""],
  'Sol Phrygien (parent: Ré# majeur)' : ["sol", "sol#", "la#", "do", "ré", "ré#", "fa",""],
  'Sol# Phrygien (parent: Mi majeur)' : ["sol#", "la", "si", "do#", "ré#", "mi", "fa#",""],
  'La Phrygien (parent: Fa majeur)' : ["la", "la#", "do", "ré", "mi", "fa", "sol",""],
  'La# Phrygien (parent: Fa# majeur)' : ["la#", "si", "do#", "ré#", "fa", "fa#", "sol#",""],
  'Si Phrygien (parent: Sol majeur)' : ["si", "do", "ré", "mi", "fa#", "sol", "la",""],

  // Lydian - parent is a perfect fourth below
  'Do Lydienne (parent: Sol majeur)' : ["do", "ré", "mi", "fa#", "sol", "la", "si",""],
  'Do# Lydienne (parent: Sol# majeur)' : ["do#", "ré#", "fa", "sol", "sol#", "la#", "do",""],
  'Ré Lydienne (parent: La majeur)' : ["ré", "mi", "fa#", "sol#", "la", "si", "do#",""],
  'Ré# Lydienne (parent: La# majeur)' : ["ré#", "fa", "sol", "la", "la#", "do", "ré",""],
  'Mi Lydienne (parent: Si majeur)' : ["mi", "fa#", "sol#", "la#", "si", "do#", "ré#",""],
  'Fa Lydienne (parent: Do majeur)' : ["fa", "sol", "la", "si", "do", "ré", "mi",""],
  'Fa# Lydienne (parent: Do# majeur)' : ["fa#", "sol#", "la#", "do", "do#", "ré#", "fa",""],
  'Sol Lydienne (parent: Ré majeur)' : ["sol", "la", "si", "do#", "ré", "mi", "fa#",""],
  'Sol# Lydienne (parent: Ré# majeur)' : ["sol#", "la#", "do", "ré", "ré#", "fa", "sol",""],
  'La Lydienne (parent: Mi majeur)' : ["la", "si", "do#", "ré#", "mi", "fa#", "sol#",""],
  'La# Lydienne (parent: Fa majeur)' : ["la#", "do", "ré", "mi", "fa", "sol", "la",""],
  'Si Lydienne (parent: Fa# majeur)' : ["si", "do#", "ré#", "fa", "fa#", "sol#", "la#",""],

  // Mixolydian - parent is a perfect fifth below
  'Do Mixolydienne (parent: Fa majeur)' : ["do", "ré", "mi", "fa", "sol", "la", "la#",""],
  'Do# Mixolydienne (parent: Fa# majeur)' : ["do#", "ré#", "fa", "fa#", "sol#", "la#", "si",""],
  'Ré Mixolydienne (parent: Sol majeur)' : ["ré", "mi", "fa#", "sol", "la", "si", "do",""],
  'Ré# Mixolydienne (parent: Sol# majeur)' : ["ré#", "fa", "sol", "sol#", "la#", "do", "do#",""],
  'Mi Mixolydienne (parent: La majeur)' : ["mi", "fa#", "sol#", "la", "si", "do#", "ré",""],
  'Fa Mixolydienne (parent: La# majeur)' : ["fa", "sol", "la", "la#", "do", "ré", "ré#",""],
  'Fa# Mixolydienne (parent: Si majeur)' : ["fa#", "sol#", "la#", "si", "do#", "ré#", "mi",""],
  'Sol Mixolydienne (parent: Do majeur)' : ["sol", "la", "si", "do", "ré", "mi", "fa",""],
  'Sol# Mixolydienne (parent: Do# majeur)' : ["sol#", "la#", "do", "do#", "ré#", "fa", "fa#",""],
  'La Mixolydienne (parent: Ré majeur)' : ["la", "si", "do#", "ré", "mi", "fa#", "sol",""],
  'La# Mixolydienne (parent: Ré# majeur)' : ["la#", "do", "ré", "ré#", "fa", "sol", "sol#",""],
  'Si Mixolydienne (parent: Mi majeur)' : ["si", "do#", "ré#", "mi", "fa#", "sol#", "la",""],

  // Locrian - parent is a minor seventh below
  'Do Locrienne (parent: Ré# majeur)' : ["do", "do#", "ré#", "fa", "fa#", "sol#", "la#",""],
  'Do# Locrienne (parent: Mi majeur)' : ["do#", "ré", "mi", "fa#", "sol", "la", "si",""],
  'Ré Locrienne (parent: Fa majeur)' : ["ré", "ré#", "fa", "sol", "sol#", "la#", "do",""],
  'Ré# Locrienne (parent: Fa# majeur)' : ["ré#", "mi", "fa#", "sol#", "la", "si", "do#",""],
  'Mi Locrienne (parent: Sol majeur)' : ["mi", "fa", "sol", "la", "la#", "do", "ré",""],
  'Fa Locrienne (parent: Sol# majeur)' : ["fa", "fa#", "sol#", "la#", "do", "do#", "ré#",""],
  'Fa# Locrienne (parent: La majeur)' : ["fa#", "sol", "la", "si", "do", "ré", "mi",""],
  'Sol Locrienne (parent: La# majeur)' : ["sol", "sol#", "la#", "do", "so#", "ré#", "fa"],
  'Sol# Locrienne (parent: Si majeur)' : ["sol#", "la", "si", "do#", "ré", "mi", "fa#",""],
  'La Locrienne (parent: Do majeur)' : ["la", "la#", "do", "ré", "ré#", "fa", "sol",""],
  'La# Locrienne (parent: Do# majeur)' : ["la#", "si", "do#", "ré#", "mi", "fa#", "sol#",""],
  'Si Locrienne (parent: Ré majeur)' : ["si", "do", "ré", "mi", "fa", "sol", "la",""],

  ' Do unitonique' :  ["do", "ré", "mi", "fa#", "sol#", "la#", "",],
  ' Do# unitonique' : ["do#", "ré#", "fa", "sol", "la", "si", "",],
  ' Ré unitonique' :  ["ré", "mi", "fa#", "sol#", "la#", "do", "",],
  ' Ré# unitonique' : ["ré#", "fa", "sol", "la", "si", "do#", "",""],
  ' Mi unitonique' :  ["mi", "fa#", "sol#", "la#", "do", "ré", "",""],
  ' Fa unitonique' :  ["fa", "sol", "la", "si", "do#", "ré#", "",""],
  ' Fa# unitonique' : ["fa#", "sol#", "la#", "do", "ré", "mi", "",""],
  ' Sol unitonique' : ["sol", "la", "si", "do#", "ré#", "fa", ""],
  ' Sol# unitonique' :["sol#", "la#", "do", "ré", "mi", "fa#", "",""],
  ' La unitonique' :  ["la", "si", "do#", "ré#", "fa", "sol", "",""],
  ' La# unitonique' : ["la#", "do", "ré", "mi", "fa#", "sol#", "",""],
  ' Si unitonique' :  ["si", "do#", "ré#", "fa", "sol", "la", "",""],
};

function allStuff(){
  let notes=[...Array(7)].map((_,i)=>document.getElementById("note"+i).value);
  // Do whatever you need with notes...
}
function checkBoxes(){
  for(let x=1;x<73;x++){
    let e=document.querySelector("#n"+x);
    e.checked=valuesToFind.includes(e.value);
    let c={do:'red', 'do#':'coral', ré:'orange', 'ré#':'gold', mi:'yellow', fa:'green', 'fa#':'cyan', sol:'blue', 'sol#':'indigo', la:'violet', 'la#':'pink', si:'brown'};
    e.style="accent-color:"+(c[e.value]||'');
  }
}